# Generated by Django 2.2 on 2020-03-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200303_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='prinority',
            new_name='priority',
        ),
    ]
